ai/easings.net

- i18n/fr.yml
I didn't correct everything though
> Some corrections on the french translations

- i18n/it.yml
I have fixed the italian translation.
> Fix italian i18n

- i18n/fr.yml
As suggested in comments at ai#47
> Fix French translation mistakes

- i18n/fa.yml
hi, i just added persian translate.
and it must be used in rtl direction to have good view.
hope it helps.
Regards
> add persian transle

- i18n/az.yml
Azerbaijani version is created.
> Azerbaijani translation

- i18n/ko.yml
Hello!
I've added the Korean translate file.
See you :^D
👍
> Add ko translation

- i18n/tr.yml
contact : sayiliromer@gmail.com
> Turkish translation

- styles/style.sass
> Add z-index to 'easing-title' 

- i18n/fr.yml
Hi! Thanks for the nice tool. Just a small typo fix.
> fix typo in french translation

- src/footer/footer.pug
Just realized that links in footer section are not correct :)
> Fix footer links

- src/easings.yml
I updated the easing numbers to better approximate Robert Penner's equations.
> Better approximation of Robert Penner's equations

- i18n/es-mx.yml
Translated the messages for the site but I couldn't test it since I got this error
"Cannot GET /es-mx"
I still haven't figured out what I might be doing wrong, I'll keep on reading to test it correctly, however here I uploaded the translation anyway.
> Added Spanish (Mexico) translation

- i18n/nl.yml
Seems like I messed up earlier by not looking at the context for one particular group of translations; I fixed the translations accordingly to the context now.
Sorry lol
> One final change to the Dutch translation

- i18n/ar.yml
Added the file ar.yml which is the translation for the standard Arabic Language.
> Added Arabic Language translation

- src/easings/easingsFunctions.ts
Hello, first of all thank you for these easing functions, they are great! Secondly I thought I would add a type and an interface to the easingsFunctions.ts file to make it a bit tidier. Cheers!
> add EasingFunction type and EasingDictionary interface

- i18n/en.yml
> remove stray apostrophe

- i18n/id.yml
Fix `id_yml` from wrong translation and untranslated word.
> Fix indonesian translation

- i18n/vi.yml
Make it less like google translated 😅, I also keep the "easing" word as from the EN version since there's no Vietnamese word that correctly describes this concept.
> Rephrase VI translation

- i18n/tr.yml
- Some typos were fixed
- Minor changes on wording to better reflect original text
> Typos and minor changes on wording

- ro.yml
Romanian language file has been added. Should make for a good base, though some wording may be a bit off based on region.
> Added romanian translation

- src/easings.yml
- use functions from Math object instead of undefined ones
> code examples that works without tweaks

- src/easings.yml
Related to #165. 
This is my first commit to this repository.
> Change sqrt() to Math.sqrt() in easeOutCirc

- i18n/lb.yml
Added translation to the luxembourgish language.
> Add Luxembourgish Translation

- i18n/no-bok.yml
Added a translation for the norwegian written language "bokmål"
> Added norwegian bokmål language translation
